/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_SayHello */

#ifndef _Included_sample_SayHello
#define _Included_sample_SayHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_SayHello
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_SayHello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
